INFO     - 2020-08-27 15:01:20,464 - [__main__ main 113] Output files will be saved in result/f0d90f695b044e72cd1f75f5d6c2b0ac7d847898-73529d64-538a247b
INFO     - 2020-08-27 15:01:20,464 - [utils log_versions 9] 3.7.3 (default, Apr 24 2020, 18:51:23) 
[Clang 11.0.3 (clang-1103.0.32.62)]
INFO     - 2020-08-27 15:01:20,556 - [utils log_versions 10] absl-py==0.9.0,aiohttp==3.6.2,appnope==0.1.0,argon2-cffi==20.1.0,astunparse==1.6.3,async-timeout==3.0.1,attrs==19.3.0,backcall==0.2.0,bleach==3.1.5,bokeh==2.2.0,cached-property==1.5.1,cachetools==4.1.1,certifi==2020.6.20,cffi==1.14.1,chainer==7.7.0,chainerrl==0.8.0,chardet==3.0.4,cloudpickle==1.3.0,colorama==0.4.3,coloredlogs==14.0,crowdai-api==0.1.22,cycler==0.10.0,DateTime==4.3,decorator==4.4.2,defusedxml==0.6.0,dill==0.3.2,entrypoints==0.3,filelock==3.0.12,future==0.18.2,gast==0.3.3,getch==1.0,gitdb==4.0.5,GitPython==3.1.7,google-auth==1.20.1,google-auth-oauthlib==0.4.1,google-pasta==0.2.0,grpcio==1.31.0,gym==0.17.2,h5py==2.10.0,humanfriendly==8.2,idna==2.10,importlib-metadata==1.7.0,ipykernel==5.3.4,ipython==7.17.0,ipython-genutils==0.2.0,ipywidgets==7.5.1,jedi==0.17.2,Jinja2==2.11.2,joblib==0.16.0,json5==0.9.5,jsonschema==3.2.0,jupyter==1.0.0,jupyter-client==6.1.6,jupyter-console==6.1.0,jupyter-core==4.6.3,jupyter-lsp==0.9.1,jupyter-server-proxy==1.5.0,jupyterlab==2.2.6,jupyterlab-git==0.20.0,jupyterlab-nvdashboard==0.4.0,jupyterlab-server==1.2.0,jupytext==1.5.2,Keras-Preprocessing==1.1.2,kiwisolver==1.2.0,lxml==4.5.2,Markdown==3.2.2,MarkupSafe==1.1.1,matplotlib==3.3.1,-e git+https://github.com/minerllabs/minerl@5d2a86cd3dd6f856207632df298f4ad9541e01eb#egg=minerl,mistune==0.8.4,multidict==4.7.6,nbconvert==5.6.1,nbdime==2.0.0,nbformat==5.0.7,notebook==6.1.1,numpy==1.19.1,oauthlib==3.1.0,opencv-python==4.2.0.34,opt-einsum==3.3.0,packaging==20.4,pandas==1.1.1,pandocfilters==1.4.2,parso==0.7.1,pexpect==4.8.0,pfrl==0.1.0,pickleshare==0.7.5,Pillow==7.2.0,pip==20.0.2,prometheus-client==0.8.0,prompt-toolkit==3.0.5,protobuf==3.12.4,psutil==5.7.2,ptyprocess==0.6.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.20,pydot==1.4.1,pyglet==1.5.0,Pygments==2.6.1,pynvml==8.0.4,pyparsing==2.4.7,Pyro4==4.80,pyrsistent==0.16.0,python-dateutil==2.8.1,python-gitlab==2.4.0,pytz==2020.1,PyYAML==5.3.1,pyzmq==19.0.2,qtconsole==4.7.5,QtPy==1.9.0,redis==3.5.3,requests==2.24.0,requests-oauthlib==1.3.0,rsa==4.6,scikit-learn==0.23.2,scipy==1.5.2,Send2Trash==1.5.0,serpent==1.30.2,setuptools==46.1.3,simpervisor==0.3,six==1.15.0,sklearn==0.0,smmap==3.0.4,tensorboard==2.3.0,tensorboard-plugin-wit==1.7.0,tensorflow==2.3.0,tensorflow-estimator==2.3.0,termcolor==1.1.0,terminado==0.8.3,testpath==0.4.4,threadpoolctl==2.1.0,toml==0.10.1,torch==1.6.0,tornado==6.0.4,tqdm==4.48.2,traitlets==4.3.3,typing==3.7.4.3,typing-extensions==3.7.4.2,urllib3==1.25.10,wcwidth==0.2.5,webencodings==0.5.1,Werkzeug==1.0.1,wheel==0.34.2,widgetsnbextension==3.5.1,wrapt==1.12.1,yarl==1.5.1,zipp==3.1.0,zope.interface==5.1.0
INFO     - 2020-08-27 15:01:20,561 - [cached_kmeans cached_kmeans 19] Load dataset & do kmeans
ERROR    - 2020-08-27 15:01:20,561 - [__main__ main 120] execution failed.
Traceback (most recent call last):
  File "mod/dqn_family.py", line 118, in main
    _main(args)
  File "mod/dqn_family.py", line 139, in _main
    random_state=args.seed)
  File "/Users/ashe/workspace/MineRL/baselines/minerl2020_pdddqn_submission/mod/cached_kmeans.py", line 20, in cached_kmeans
    kmeans = _do_kmeans(env_id=env_id, n_clusters=n_clusters, random_state=random_state)
  File "/Users/ashe/workspace/MineRL/baselines/minerl2020_pdddqn_submission/mod/cached_kmeans.py", line 35, in _do_kmeans
    dat = minerl.data.make(env_id)
  File "/Users/ashe/.local/share/virtualenvs/MineRL-APCPXVva/src/minerl/minerl/data/__init__.py", line 38, in make
    raise ValueError("No data_dir provided and $MINERL_DATA_ROOT undefined."
ValueError: No data_dir provided and $MINERL_DATA_ROOT undefined.Specify force_download=True to download default dataset
